config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#landing'
  get   '/home'     => 'pages#home', as: 'home'

  get   '/login'    => 'session#new'        # show the login form
  post  '/login'    => 'session#create'     # form submits to here, performs login, redirect
  delete '/login'   => 'session#destroy'    # logout link goes here, performs logout, redirect
  
  
  resources :users, except: [:show]
  
  resources :suits
  resources :carts, except: [:new, :edit, :update, :destroy]
  get 'thanks', to: 'carts#thanks', as: 'thanks'
  resources :profiles
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user, optional: true
    has_many :suits

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :check_if_logged_in
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new profile_params
    @profile.user_id = @current_user.id
    @profile.save

    if @profile.persisted?
      redirect_to profiles_path
    else
      render :new
    end

  end

  def index
    @profiles = @current_user.profiles
  end

  def show
    @profile = Profile.find params[:id]
    redirect_to home_path unless @profile.user_id == @current_user.id
    @suits = @profile.suits
  end

  def edit
    @profile = Profile.find params[:id]
    redirect_to home_path unless @profile.user_id == @current_user.id
  end

  def update
    @profile = Profile.find params[:id]

    if @profile.user_id != @current_user.id
      redirect_to home_path
      return
    end

    @profile.update profile_params

    if @profile.persisted?
      redirect_to profile_path(@profile)
      return
    else
      render :edit
    end
    redirect_to profile_path(@profile)
    return
  end

  def destroy
    Profile.destroy params[:id]
    redirect_to profiles_path
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :gender, :height, :weight, :shoulders, :neck, :chest, :bicep, :forearm, :wrist, :sleeve, :front_length, :back_length, :mid_waist, :waist, :hip, :upper_thigh, :middle_thigh, :calf, :ankle, :pants_length, :crotch)
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<% if @profile.errors.any? %>
    <ul>
        <% @profile.errors.full_messages do |e| %>
        <li>
            <%= e %>
        </li>
        <% end %>
    </ul>    
<% end %>


<%= form_with model: @profile, local: true do |f| %>

    <div class = 'form'>
        <%= f.label :name %>
        <br>
        <%= f.text_field :name, required: true %>
    </div>
    <br>
    
    <br>
    <div class = 'form'>
        <%= f.radio_button :gender, 'Male' %>
        <%= f.label :gender_male, 'Male' %>

        <%= f.radio_button :gender, 'Female' %>
        <%= f.label :gender_female, 'Female' %>
    </div>
    <br>
    
    <br>
    <div class = 'form'>
        <%= f.label :height %>
        (cm)
        <br>
        <%= f.number_field :height, required: true %>
    </div>
    <br>
    
    <br>
    <div class = 'form'>
        <%= f.label :weight %>
        (kg)
        <br>
        <%= f.number_field :weight, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>

        
            <%= image_tag("f-shoulders.jpeg", class: 'form-image') %>
            <%= image_tag("m-shoulders.png", class: 'form-image') %>
        
        <p>Apply small pressure to find the bone on each
end of the shoulders, and measure from seam
to seam.</p>
        <%= f.label :shoulders %>
        (cm)
        <br>
        <%= f.number_field :shoulders, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>

        
            <%= image_tag("f-neck.jpeg", class: 'form-image') %>
            <%= image_tag("m-neck.png", class: 'form-image') %>

        <p>Measure near the base of your neck. Leave
one finger width in between the tape and
neck (depending on preferred tightness)
</p>
        <%= f.label :neck %>
        (cm)
        <br>
        <%= f.number_field :neck, required: true%>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>

        
            <%= image_tag("f-chest.jpeg", class: 'form-image') %>
            <%= image_tag("m-chest.png", class: 'form-image') %>
    
        <p>Wrap measuring tape all around your chest.
Ensure the tape is directly under the armpits
and is level.
</p>
        <%= f.label :chest %>
        (cm)
        <br>
        <%= f.number_field :chest, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
       
            <%= image_tag("f-bicep.jpeg", class: 'form-image') %>
            <%= image_tag("m-bicep.png", class: 'form-image') %>
        
        <p>Measure around the widest part of your bicep.
</p>
        <%= f.label :bicep %>
        (cm)
        <br>
        <%= f.number_field :bicep, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("m-forearm.png", class: 'form-image') %>
       
        <p>Wrap the measuring tape around the thickest
area of your forearm.</p>
        <%= f.label :forearm %>
        (cm)
        <br>
        <%= f.number_field :forearm, required: true%>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("m-wrist.png", class: 'form-image') %>
        
        <p>Measure around the wrist (on skin).</p>
        <%= f.label :wrist %>
        (cm)
        <br>
        <%= f.number_field :wrist, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("f-sleeve.jpeg", class: 'form-image') %>
            <%= image_tag("m-sleeve.png", class: 'form-image') %>
        
        <p>Measure from the 't seam' on the shoulder to
the start of your wrist.</p>
        <%= f.label :sleeve %>
        (cm)
        <br>
        <%= f.number_field :sleeve, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("m-frontlength.png", class: 'form-image') %>
        
        <p>Measure from top of your traps and straight
down to between your first and second thumb
knuckle.
</p>
        <%= f.label :front_length %>
        (cm)
        <br>
        <%= f.number_field :front_length, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("f-backlength.jpeg", class: 'form-image') %>
            <%= image_tag("m-backlength.png", class: 'form-image') %>
       
        <p>Measure from top of your traps down to
desired length. Typically within 0.5 centimetres of your
front length.
</p>
        <%= f.label :back_length %>
        (cm)
        <br>
        <%= f.number_field :back_length, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("f-midwaist.jpeg", class: 'form-image') %>
            <%= image_tag("m-midwaist.png", class: 'form-image') %>
        
        <p>Measure around your waist area from your
belly button. Ensure the tape is level.
</p>
        <%= f.label :mid_waist %>
        (cm)
        <br>
        <%= f.number_field :mid_waist, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("f-waist.jpeg", class: 'form-image') %>
            <%= image_tag("m-waist.png", class: 'form-image') %>
       
        <p>Measure around your waist, on or slightly
above where you usually wear your pants.
Adjust to your preferred tightness.</p>
        <%= f.label :waist %>
        (cm)
        <br>
        <%= f.number_field :waist, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("f-hip.jpeg", class: 'form-image') %>
            <%= image_tag("m-hip.png", class: 'form-image') %>
        
        <p>Place your feet together and measure around
the widest part of your hips. Ensure the tape is
straight and level.
</p>
        <%= f.label :hip %>
        (cm)
        <br>
        <%= f.number_field :hip, required: true%>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("f-upperthigh.jpeg", class: 'form-image') %>
            <%= image_tag("m-upperthigh.png", class: 'form-image') %>
        
        <p>Measure around the thickest part of your upper
thigh. Typically below the groin area.</p>
        <%= f.label :upper_thigh %>
        (cm)
        <br>
        <%= f.number_field :upper_thigh, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
       
            <%= image_tag("m-middlethigh.png", class: 'form-image') %>
        

        <p>Measure around the middle of your thigh.
Typically found 10 centimetres above your knee cap.</p>
        <%= f.label :middle_thigh %>
        (cm)
        <br>
        <%= f.number_field :middle_thigh, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("f-calf.jpeg", class: 'form-image') %>
            <%= image_tag("m-calf.png", class: 'form-image') %>
        
        <p>Measure around the widest part of your calf.
</p>
        <%= f.label :calf %>
        (cm)
        <br>
        <%= f.number_field :calf, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("m-ankle.png", class: 'form-image') %>
        
        <p>Measure around your ankle (on skin).</p>
        <%= f.label :ankle %>
        (cm)
        <br>
        <%= f.number_field :ankle, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("f-pantslength.jpeg", class: 'form-image') %>
            <%= image_tag("m-pantslength.png", class: 'form-image') %>
        
        <p>Measure from the top of the waistband to the
bottom of your feet.</p>
        <%= f.label :pants_length %>
        (cm)
        <br>
        <%= f.number_field :pants_length, required: true %>
    </div>
    <br>
    <hr>
    <br>
    <div class = 'form'>
        
            <%= image_tag("f-crotch.jpeg", class: 'form-image') %>
            <%= image_tag("m-crotch.png", class: 'form-image') %>
        
        <p>Measure from front waist line to back waist
line. Keep it tight but squat to ensure there is
no discomfort.</p>
        <%= f.label :crotch %>
        (cm)
        <br>
        <%= f.number_field :crotch, required: true %>
    </div>
    <br>

    
    <br>
    <%= f.submit %>
<% end %>
    

app/views/profiles/edit.html.erb
<h1>Edit <%= @profile.name %>'s profile</h1>
<br>
<%= render partial: 'form' %>

app/views/profiles/index.html.erb
<h1>Profiles</h1>
<%= link_to "New Profile", new_profile_path %>


    <% @profiles.each do |p| %>
        <p>
            <%= link_to p.name, profile_path(p) %>
            |
            <%= link_to 'Edit', edit_profile_path(p)  %>
        </p>

    <% end %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>
<br>
<%= render partial: 'form' %>

app/views/profiles/show.html.erb
<h1><%= @profile.name %>'s Profile</h1>
<%= link_to 'Edit', edit_profile_path(@profile)  %>
|
<%= link_to 'Delete', profile_path(@profile), method: 'delete' %>
<br>
<div>
    <h3>
        Gender: <%= @profile.gender %>
    </h3>

    <h3>
        Height: <%= @profile.height %>cm
    </h3>

    <h3>
        Weight: <%= @profile.weight %>kg
    </h3>

    <h3>
        Shoulders: <%= @profile.shoulders %>cm
    </h3>

    <h3>
        Neck: <%= @profile.neck %>cm
    </h3>

    <h3>
        Chest: <%= @profile.chest %>cm
    </h3>

    <h3>
        Bicep: <%= @profile.bicep %>cm
    </h3>

    <h3>
        Forearm: <%= @profile.wrist %>cm
    </h3>

    <h3>
        Sleeve: <%= @profile.sleeve %>cm
    </h3>

    <h3>
        Front Length: <%= @profile.front_length %>cm
    </h3>

    <h3>
        Back Length: <%= @profile.back_length %>cm
    </h3>

    <h3>
        Mid Waist: <%= @profile.mid_waist %>cm
    </h3>

    <h3>
        Waist: <%= @profile.waist %>cm
    </h3>

    <h3>
        Hip: <%= @profile.hip %>cm
    </h3>

    <h3>
        Upper Thigh: <%= @profile.upper_thigh %>cm
    </h3>

    <h3>
        Middle Thigh: <%= @profile.middle_thigh %>cm
    </h3>

    <h3>
        Calf: <%= @profile.calf %>cm
    </h3>

    <h3>
        Ankle: <%= @profile.ankle %>cm
    </h3>

    <h3>
        Pants Length: <%= @profile.pants_length %>cm
    </h3>

    <h3>
        Crotch: <%= @profile.crotch %>cm
    </h3>
</div>

<h1>Order History</h1>
<ul>
    <% @suits.each do |s| %>
        <li>
            <%= link_to "##{s.id} - #{s.jacket_fit} #{s.design}",  suit_path(s)%>
        </li>

    <% end %>
</ul>