config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#landing'
  get   '/home'     => 'pages#home', as: 'home'

  get   '/login'    => 'session#new'        # show the login form
  post  '/login'    => 'session#create'     # form submits to here, performs login, redirect
  delete '/login'   => 'session#destroy'    # logout link goes here, performs logout, redirect
  
  
  resources :users, except: [:show]
  
  resources :suits
  resources :carts, except: [:new, :edit, :update, :destroy]
  get 'thanks', to: 'carts#thanks', as: 'thanks'
  resources :profiles
end

app/models/suit.rb
class Suit < ApplicationRecord
    belongs_to :profile, optional: true
    belongs_to :cart, optional: true
end

app/controllers/suits_controller.rb
class SuitsController < ApplicationController
  before_action :check_if_logged_in # Don't want anyone but the user to do anything here
  def new
    @suit = Suit.new
  end

  def create
    @suit = Suit.new suit_params # The form will contain profile_id
    @suit.shirt_length = @suit.profile.front_length + 3   # The following params are calculated automatically without user input
    @suit.shirt_sleeve_length = @suit.profile.sleeve + 1
    @suit.price = @suit.quality * 5 + @suit.extra_shirts * 100 + (@suit.extra_pants + @suit.extra_jackets) * @suit.quality
    @suit.cart_id = @current_user.cart.id
    @suit.paid = false
    @suit.save

      if @suit.persisted?

        

        redirect_to suits_path
      else
        render :new
      end

  end

  def index
    @suits = @current_user.suits
  end

  def show
    @suit = Suit.find params[:id]
    redirect_to home_path unless @suit.profile.user_id == @current_user.id
  end

  def edit
    @suit = Suit.find params[:id]
    
    redirect_to home_path unless @suit.profile.user_id == @current_user.id || @suit.paid
  end

  def update
    @suit = Suit.find params[:id]


    if @suit.profile.user_id != @current_user.id
      redirect_to home_path
      return
    end

    @suit.update suit_params
    @suit.shirt_length = @suit.profile.front_length + 3   # The following params are calculated automatically without user input
    @suit.shirt_sleeve_length = @suit.profile.sleeve + 1
    @suit.price = @suit.quality * 5 + @suit.extra_shirts * 100 + (@suit.extra_pants + @suit.extra_jackets) * @suit.quality
    @suit.save

    if @suit.persisted?
      redirect_to suit_path(@suit)
      return
    else
      render :edit
    end
    redirect_to suit_path(@suit)
    return
  end

  def destroy
    Suit.destroy params[:id]
    redirect_to suits_path
  end

  private

  def suit_params
    params.require(:suit).permit(:design, :jacket_fit, :pants_fit, :jacket_pocket_style, :jacket_pockets, :jacket_buttons, :inner_lining_color, :vents, :lapel, :inner_lining_name, :shirt_chest_pocket, :shirt_collar, :shirt_cuff, :shirt_initials, :extra_shirts, :extra_pants, :extra_jackets, :quality, :notes, :profile_id
    )
  end

end

app/helpers/suits_helper.rb
module SuitsHelper
end

app/views/suits/_form.html.erb
<% if @suit.errors.any? %>
    <ul>
        <% @suit.errors.full_messages do |e| %>
        <li>
            <%= e %>
        </li>
        <% end %>
    </ul>    
<% end %>

<%= form_with model: @suit, local: true do |f| %>
    <div class = 'form'>
        <%= f.label :profile_id %>
        <br>
        <%= f.select :profile_id, @current_user.profiles.collect {|u| [u.name, u.id]}, prompt: true, required: true %>
    </div>
    <br>
    <br>
    <div class = 'form'>
        <%= f.label :design %>
        <br>
        <%= f.select :design, ['Tuxedo', 'Double-Breasted', 'Femme Skirt', 'Other'] , prompt: true, required: true %>
    </div>
    <br>
    <br>
    <div class = 'form'>
        <%= f.label :Quality %>
        <br>
        Super <%= f.select :quality, [100, 150, 200, 250], prompt: true, required: true %>  
    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :jacket_fit %>
        <br>
        <%= f.select :jacket_fit, ['Slim', 'Straight'] , prompt: true, required: true %>
    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :pants_fit %>
        <br>
        <%= f.select :pants_fit, ['Slim', 'Straight'] , prompt: true, required: true %>
    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :jacket_pocket_style %>
        <br>
        <%= f.select :jacket_pocket_style, ['Slanted','Straight', 'Slanted No Flaps', 'Straight No Flaps'], prompt: true, required: true %>   
    </div>
    <br><br>

    <div class = 'form'>
        <%= f.label :jacket_buttons %>
        <br>
        <%= f.select :jacket_buttons, [0, 1, 2, 3], prompt: true, required: true %>   
    </div>
    <br><br>

    <div class = 'form'>
        <%= f.label :inner_lining_color %>
        <br>
        <%= f.select :inner_lining_color, ['White','Black', 'Red', 'Blue'], prompt: true, required: true %>   
    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :inner_lining_name %>
        <br>
        <%= f.text_field :inner_lining_name %>
    </div>
    <br><br>

    <div class = 'form'>
        <%= f.label 'Number of Vents' %>
        <br>
        <%= image_tag("vent0.png", class: 'form-image', alt: 'vent0') %> 

        <%= image_tag("vent1.png", class: 'form-image', alt: 'vent1') %>

        <%= image_tag("vent2.png", class: 'form-image', alt: 'vent2') %> 
        <br>
        <%= f.select :vents, [0, 1, 2], prompt: true, required: true %>

    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :lapel %>
        <br>
        <%= image_tag("notch.png", class: 'form-image', alt: 'notch') %> 

        <%= image_tag("peak.png", class: 'form-image', alt: 'peak') %>

        <%= image_tag("shawl.png", class: 'form-image', alt: 'shawl') %> 
        <br>
        <%= f.select :lapel, ['Notch', 'Peak', 'Shawl'], prompt: true, required: true %>

    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :shirt_cuff %>
        <br>
        <%= image_tag("Barel.png", class: 'form-image', alt: 'Barel') %> 

        <%= image_tag("French-Cuff.png", class: 'form-image', alt: 'French-Cuff') %>

        <%= image_tag("Mitered.png", class: 'form-image', alt: 'Mitered') %> 
 
        <br>
        <%= f.select :shirt_cuff, ['Barel', 'French Cuff', 'Mitered'], prompt: true, required: true %>

    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :shirt_collar %>
        <br>
        <%= image_tag("button-down.png", class: 'form-image', alt: 'button-down') %> 

        <%= image_tag("cutaway.png", class: 'form-image', alt: 'cutaway') %>

        <%= image_tag("spread-collar.png", class: 'form-image', alt: 'spread-collar') %> 

        <%= image_tag("wing-tip.png", class: 'form-image', alt: 'wing-tip') %> 
        <br>
        <%= f.select :shirt_collar, ['Button Down', 'Cutaway', 'Spread Collar', 'Straight Point', 'Wing Tip'], prompt: true, required: true %>

    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :shirt_chest_pocket %>
        <br>
        <%= f.select :shirt_chest_pocket, [true, false], prompt: true, required: true %>   
    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :shirt_initials %>
        <br>
        <%= f.text_field :shirt_initials%>
    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :extra_shirts %>
        <br>
        <%= f.number_field :extra_shirts, required: true, :value => 0 %>
    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :extra_pants %>
        <br>
        <%= f.number_field :extra_pants, required: true, :value => 0 %>
    </div>
    <br><br>
    <div class = 'form'>
        <%= f.label :extra_jackets %>
        <br>
        <%= f.number_field :extra_jackets, required: true, :value => 0 %>
    </div>
    <br><br>
    <div class = 'form'>
        Extra <%= f.label :notes %>
        <br>
        <%= f.text_area :notes %>
    </div>
    <br><br>

    <%= f.submit %>
<% end %>

app/views/suits/edit.html.erb
<h1>Edit Suit Order</h1>

<%= render partial: 'form' %>

app/views/suits/index.html.erb
<h1>Order History</h1>

<%= link_to "Create Order", new_suit_path %>


    <% @suits.each do |s| %>
    <p>
        <% unless s.paid %>
            Pending Payment For
        <% end %>
        <%= link_to "##{s.id} - #{s.jacket_fit} #{s.design}",  suit_path(s)%>
        |
        <%= link_to s.profile.name, profile_path(s.profile) %>

        <% unless s.paid %>
            |
            <%= link_to 'Edit', edit_suit_path(s) %>
            |
            <%= link_to 'Delete', suit_path(s), method: 'delete' %>
        <% end %>
    
    </p>
    
    <% end %>
    

app/views/suits/new.html.erb
<h1>New Suit Order</h1>

<%= render partial: 'form' %>

app/views/suits/show.html.erb
<h1>Order Details For #<%=@suit.id%> -  <%=@suit.jacket_fit%> <%=@suit.design %></h1>

<% unless @suit.paid %>
    Pending Payment 
    <br>
    <%= link_to 'Edit', edit_suit_path(@suit) %>
    |
    <%= link_to 'Delete', suit_path(@suit), method: 'delete' %>
    <br>
<% end %>
<div>
    <h3>
        Made for <%= link_to @suit.profile.name, profile_path(@suit.profile) %>
    </h3>
    <hr>
    <h2>Suit Customizations</h2>
    <h3>
        Design: <%= @suit.design %>
    </h3>

    <h3>
        Jacket Fit: <%= @suit.jacket_fit %>
    </h3>

    <h3>
        Pants Fit: <%= @suit.pants_fit %>
    </h3>

    <h3>
        Jacket Pocket Style: <%= @suit.jacket_pocket_style %>
    </h3>

    <h3>
        Number of Jacket Buttons: <%= @suit.jacket_buttons %>
    </h3>

    <h3>
        Inner Lining Colour: <%= @suit.inner_lining_color %>
    </h3>

    <h3>
        Number of Vents: <%= @suit.vents %>
    </h3>

    <h3>
        Lapel: <%= @suit.lapel %>
    </h3>

    <h3>
        Name Inside of Jacket: <%= @suit.inner_lining_name %>
    </h3>
    <hr>
    <h2>Shirt Customizations</h2>

    <h3>
        Pocket? <%= @suit.shirt_chest_pocket ? "Yes" : "No" %>
        
    </h3>

    <h3>
        Collar: <%= @suit.shirt_collar %>
    </h3>

    <h3>
        Cuff: <%= @suit.shirt_cuff %>
    </h3>

    <h3>
        Initials on Sleeve: <%= @suit.shirt_initials %>
    </h3>

    <h3>
        Length: <%= @suit.shirt_length %>
    </h3>

    <h3>
        Sleeve Length: <%= @suit.shirt_sleeve_length %>
    </h3>
    <hr>
    <h3>
        Number of Extra Jackets: <%= @suit.extra_jackets %>
    </h3>

    <h3>
        Number of Extra Shirts: <%= @suit.extra_shirts %>
    </h3>

    <h3>
        Number of Extra Pants: <%= @suit.extra_pants %>
    </h3>

    <h3>
        Quality: Super <%= @suit.quality %>s
    </h3>

    <h3>
        Price: $<%= @suit.price %>
    </h3>

    <h3>
        Notes: <%= @suit.notes %>
    </h3>
</div>