config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#landing'
  get   '/home'     => 'pages#home', as: 'home'

  get   '/login'    => 'session#new'        # show the login form
  post  '/login'    => 'session#create'     # form submits to here, performs login, redirect
  delete '/login'   => 'session#destroy'    # logout link goes here, performs logout, redirect
  
  
  resources :users, except: [:show]
  
  resources :suits
  resources :carts, except: [:new, :edit, :update, :destroy]
  get 'thanks', to: 'carts#thanks', as: 'thanks'
  resources :profiles
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user, optional: true
    has_many :suits
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :check_if_logged_in
  before_action :find_total_price
  def thanks
    remove_purchased_suits_from_cart
  end

  def create
  
    # This should be in a different controller, but I can't figure out how to achieve dynamic pricing otherwise, so this will do for now
    @amount = @total_price * 100 # This informs the stripe API how much to charge
  
    # Stripe models
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )
  
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'aud'
    )
  

    
    redirect_to thanks_path
    # Error checking
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to home_path
    
  end

  def show
    @cart = Cart.find params[:id]
    unless @cart.user_id == @current_user.id
      redirect_to home_path
      return
    end
  
    # Need to find the total price of the cart
    @cart_price = @total_price
  end


  private


  def find_total_price
    cart = @current_user.cart
    @total_price = 0;
    # loop through suits to add their prices
    cart.suits.each do |s|
      @total_price += s.price
    end
    @total_price #return total price
  end

  def remove_purchased_suits_from_cart
    cart = @current_user.cart
    cart.suits.each do |s|
      s.update :paid => true
      cart.suits.delete(s)
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/new.html.erb
<h1>Shopping Cart</h1>
<% @cart.suits.each do |s| %>

<h3>
Suit #<%=s.id%> - <%=s.jacket_fit%> <%=s.design%>
|
<%= link_to 'Edit', edit_suit_path(s) %>
|
<%= link_to 'Delete', suit_path(s), method: 'delete' %>
<br>
Extra Jacket × <%= s.extra_jackets %>
<br>
Extra Shirt × <%= s.extra_shirts %> 
<br>
Extra Pants × <%= s.extra_pants %>
<br>
Price: $<%= s.price %>
</h3>
<hr>

<% end %>
<h2>Total Price: $<%= @total_price %></h2>
<%= form_tag carts_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="One time payment"
          data-amount="<%= @total_price * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/carts/show.html.erb
<h1>Shopping Cart</h1>
<% @cart.suits.each do |s| %>

<h3>
Suit #<%=s.id%> - <%=s.jacket_fit%> <%=s.design%>
<br>
Extra Jacket × <%= s.extra_jackets %>
<br>
Extra Shirt × <%= s.extra_shirts %> 
<br>
Extra Pants × <%= s.extra_pants %>
<br>
Price: $<%= s.price %>
<br>
<%= link_to 'Edit', edit_suit_path(s) %>
|
<%= link_to 'Delete', suit_path(s), method: 'delete' %>
</h3>
<hr>

<% end %>
<% if @cart_price > 0 %>
  <h2>Total Price: $<%= @cart_price %></h2>
  <%= form_tag carts_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="One time payment"
            data-amount="<%= @cart_price * 100 %>"
            data-locale="auto"></script>
  <% end %>
<% else %>
  <p>There's nothing here!</p>
  <%= link_to "Maybe you'd like to change that?", new_suit_path %>
<% end %>
  

app/views/carts/thanks.html.erb
<h2>Thank you for your patronage!</h2>
<p>Your order will arrive in 4 to 6 weeks.</p>