config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#landing'
  get   '/home'     => 'pages#home', as: 'home'

  get   '/login'    => 'session#new'        # show the login form
  post  '/login'    => 'session#create'     # form submits to here, performs login, redirect
  delete '/login'   => 'session#destroy'    # logout link goes here, performs logout, redirect
  
  
  resources :users, except: [:show]
  
  resources :suits
  resources :carts, except: [:new, :edit, :update, :destroy]
  get 'thanks', to: 'carts#thanks', as: 'thanks'
  resources :profiles
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lupo Bianco</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    

  </head>

  <body>

    
    <div class='main-area'>
      <div id="nav">
        <% if @current_user.present? %>
        <%= image_tag("LupoBiancoWhiteResize.png", class: "nav-logo", alt: "Lupo Bianco Custom Tailoring") %>
        <br>
        <%= link_to 'Log Out', login_path, method: 'delete' %>
        |
        <%= link_to 'Home', home_path %>
        |
        <%= link_to 'Profiles', profiles_path %>
        |
        <%= link_to 'Orders', suits_path %>
        |
        <%= link_to 'Account Settings', edit_user_path(@current_user) %>
        |
        <%= link_to 'Shopping Cart', cart_path(@current_user.cart.id) %>
        <hr>
      <% end %>
      
      </div>
      
      <%= yield %>
    </div>
  </body>
</html>